In [1]:
import os
import cv2
import numpy as np

In [2]:
x = []
y = []

In [3]:
one = os.listdir('./1/')
two = os.listdir('./2/')
three = os.listdir('./3/')

In [4]:
#print(one,two,three)

In [5]:
#number = ['one', 'two','three']

In [6]:
for i in one:
    img = cv2.imread('./1/'+i)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.resize(img, (80,80))
    img = img.flatten()
    x.append(img)
    y.append(1)
    
    #print(img.shape)

In [7]:
for i in two:
    img = cv2.imread('./2/'+i)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.resize(img, (80,80))
    img = img.flatten()
    x.append(img)
    y.append(2)
    
    #print(img.shape)

In [8]:
for i in three:
    img = cv2.imread('./3/'+i)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.resize(img, (80,80))
    img = img.flatten()
    x.append(img)
    y.append(3)
    
    #print(img.shape)

In [9]:
x = np.asarray(x)
y = np.asarray(y)

In [10]:
type(y)

numpy.ndarray

In [11]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3])

In [12]:
np.save('Numta_x.npy', x)
np.save('Numta_y.npy', y)

In [13]:
#from keras.utils.np_utils import to_categorical
from keras.utils import np_utils

C:\Users\88016\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [14]:
#y = to_categorical(y, num_classes = 10)
y=np_utils.to_categorical(y,num_classes=4)

In [15]:
y

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [16]:
import numpy as np
y= np.delete(y,np.where(~y.any(axis=0))[0], axis=1)

In [17]:
#x = np.asarray(x)
#y = np.asarray(y)

In [18]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
y.shape

(200, 3)

In [20]:
type(y)

numpy.ndarray

In [21]:
#y = to_categorical(y, num_classes = 3)

In [22]:
print(x.shape)
print(y.shape)

(200, 6400)
(200, 3)


In [23]:
import tensorflow as tf

In [24]:
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from keras.layers.normalization import BatchNormalization 
from keras.utils import np_utils

In [25]:
model = Sequential()

In [26]:
model.add(Dense(120, input_dim = 6400, activation = 'relu'))
model.add(Dense(80, activation = 'relu'))
#model.add(Dense(250, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [27]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [28]:
model.fit(x,y, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
200/200 [==============================] - 1s 4ms/step - loss: 10.6380 - acc: 0.3400
Epoch 2/100
200/200 [==============================] - 1s 3ms/step - loss: 10.6379 - acc: 0.3400
Epoch 3/100
200/200 [==============================] - 1s 3ms/step - loss: 10.6379 - acc: 0.3400
Epoch 4/100
200/200 [==============================] - 1s 3ms/step - loss: 10.6379 - acc: 0.3400
Epoch 5/100
200/200 [==============================] - 1s 3ms/step - loss: 10.6379 - acc: 0.3400
Epoch 6/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 7/100
200/200 [==============================] - 1s 3ms/step - loss: 10.6379 - acc: 0.3400
Epoch 8/100
200/200 [==============================] - 1s 3ms/step - loss: 10.6379 - acc: 0.3400
Epoch 9/100
200/200 [==============================] - 1s 3ms/step - loss: 10.6379 - acc: 0.3400
Epoch 10/100
200/200 [==============================] - 1s 3ms/step - loss: 10.

200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 82/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 83/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 84/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 85/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 86/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 87/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 88/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 89/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 90/100
200/200 [==============================] - 0s 2ms/step - loss: 10.6379 - acc: 0.3400
Epoch 91/100
200/200 [===========